language: generic
before_script:
  # Install vroom
  - wget https://github.com/google/vroom/releases/download/v0.12.0/vroom_0.12.0-1_all.deb
  - sudo dpkg -i vroom_0.12.0-1_all.deb

  # Install vim
  - sudo apt-get install vim-gnome

  # Install editorconfig
  - sudo apt-get install cmake libpcre3-dev
  - git clone https://github.com/editorconfig/editorconfig-core-c.git
  - (cd editorconfig-core-c; cmake . && sudo make install)

  # Vroom's vim mode currently requires a running X server
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - make test
